version: '3.8'

services:
  web:
    container_name: data_extraction
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development

#   mysqldb:
#     image: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=p@ssw0rd1
#     volumes:
#       - mysql:/var/lib/mysql
#       - mysql_config:/etc/mysql

# volumes:
#   mysql:
#   mysql_config:
