pipeline {
    agent any

    stages {
        stage('Build Docker Images') {
            steps {
                sh '''
                    docker build --no-cache -t app-container DataExtraction/Jenkins_Docker/app/.
                    docker build --no-cache -t aws-container DataExtraction/Jenkins_Docker/aws/.
                '''
            }
        }
    }
}